# -*- coding: utf-8 -*-
"""IoT_1015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q93N5jO92VDYCuUO65LsAWh0ISNQU-3Y
"""

!pip --version

import numpy as np
import pandas as pd

l1 = [1,2,'3',4.1]   # 리스트는 한 배열안에 다양한 자료형 가능
print(l1, type(l1))   # print(l1, type(l1))

# 넘파이 리스트 쓰면 배열 연산이 파이썬 리스트보다 훨씬 빠름 -> 빠른 연산 속도
a1 = np.array([1,2,3,4])   # 넘파이 배열 안에 자료형 다른거 쓰면 우선순위 높은애로 다 바뀜
print(a1)

a2 = np.array(l1)
print(a2, type(a2))     # ['1' '2' '3' '4.1'] <class 'numpy.ndarray'>

a3 = np.ones(2, dtype=np.int64)
print(a3, type(a3), a3.shape)     # [1 1] <class 'numpy.ndarray'> (2,)

a4 = np.zeros(5, dtype=np.int64)
print(a4, type(a4), a4.shape)     # [0 0 0 0 0] <class 'numpy.ndarray'> (5,)

# shape 같은 애들은 넘파이 속성
# zeros, ones 같은 애들은 함수